baseURL = 'https://example.org/'
languageCode = 'es-ES'
title = 'Recetas de Amama'
theme = 'ananke'
defaultContentLanguage = 'es'
sectionPagesMenu = "main"
[pagination]
  pagerSize = 10

[taxonomies]
  category = 'categories'

[menus]
[[menus.main]]
    name = 'Categorias'
    pageRef = '/categories'
    weight = 30

[[menus.main]]
    name = 'Buscar'
    pageRef = '/buscar'
    weight = 40
